version: '2'
services:
    pimcore:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html/pimcore
        links:
            - mysql
        depends_on:
            - mysql
        privileged: true
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
